version: "3.7"
services:
  db:
    image: "postgres"
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "todo"
    ports:
      - "5432:5432"
    volumes:
      - ./volume/todo:data/postgres
