version: "3.8"
services:
  db:
    image: "postgres"
    container_name: "db"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "todo"
    ports:
      - "5432:5432"
    volumes:
      - "/opt/volume/todo:/var/lib/postgresql/data"
