  name: Unit Test
  on:
    push:
     branches:
      - main
      - development
  jobs:
    test:
      name: Unit Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: '11'
        - name: Test with Gradle
          run: ./gradle test
